### ISSUE TITLE
Update - https://github.com/Atlantic18/DoctrineExtensions

### ISSUE THREAD

**Issue by john-everden** [Kaapiii/concrete5_doctrine_behavioral_extensions#1]
Any chance we can update to https://github.com/Atlantic18/DoctrineExtensions version 3.0? I'd really love to have soft deletable but it isn't available in the current version.

**Comment by Kaapiii** [comment]
That's reasonable. Possibly also increase the package version to 2.0.0.

**Comment by Kaapiii** [comment]
The new package [version 2.0.0](https://github.com/Kaapiii/concrete5_doctrine_behavioral_extensions/releases/tag/2.0.0) with the Atlantic/DoctineExtensions version 3.0 was published.

**Comment by john-everden** [comment]
Nice thanks!
